config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  
  resources :posts do
    resources :comments, :only => [:create]
  end

  root :to => 'posts#index'

  get '/archive', :to => 'pages#archive'
  get '/about', :to => 'pages#about'

  get '/404', :to => 'errors#not_found'
  get '/500', :to => 'errors#internal_error'
  get '/422', :to => 'errors#unprocessable_entity'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :body, :title

  has_many :comments

  validates_presence_of :body, :title

  def content
  render_options = {
    # will remove from the output HTML tags inputted by user
    filter_html:     true,
    # will insert <br /> tags in paragraphs where are newlines
    # (ignored by default)
    hard_wrap:       true,
    # hash for extra link options, for example 'nofollow'
    link_attributes: { rel: 'nofollow' }
    # more
    # will remove <img> tags from output
    # no_images: true
    # will remove <a> tags from output
    # no_links: true
    # will remove <style> tags from output
    # no_styles: true
    # generate links for only safe protocols
    # safe_links_only: true
    # and more ... (prettify, with_toc_data, xhtml)
  }
  renderer = Redcarpet::Render::HTML.new(render_options)

  extensions = {
    #will parse links without need of enclosing them
    autolink:           true,
    # blocks delimited with 3 ` or ~ will be considered as code block.
    # No need to indent.  You can provide language name too.
    # ```ruby
    # block of code
    # ```
    fenced_code_blocks: true,
    # will ignore standard require for empty lines surrounding HTML blocks
    lax_spacing:        true,
    # will not generate emphasis inside of words, for example no_emph_no
    no_intra_emphasis:  true,
    # will parse strikethrough from ~~, for example: ~~bad~~
    strikethrough:      true,
    # will parse superscript after ^, you can wrap superscript in ()
    superscript:        true
    # will require a space after # in defining headers
    # space_after_headers: true
  }
  Redcarpet::Markdown.new(renderer, extensions).render(body).html_safe
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)

    if(@comment.author == nil || @comment.author == "")
      @comment.author = "Anonymous"
    end

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :author)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ActionController::Base
  layout 'error'

  def not_found
  end

  def internal_error
  end

  def unprocessable_entity
  end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  layout 'application'

  def archive
    @posts = Post.order("created_at DESC").all
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => [ :index, :show ]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at desc").all
  end

  def archive 
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    # @comments = @posts.comments.order("created_at DESC").all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password == "secret"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment panel panel-default">
  <div class="panel-body">
    <%= comment.body %>
  </div>
  <div class="panel-footer">
    <small class="col-sm-6 text-left"><%= comment.author %></small>
    <small class="col-sm-6 text-right">Posted <%= time_ago_in_words(comment.created_at) %> ago</small>
  </div>
</div>

app/views/comments/create.js.erb
$('#comments').append('<%= escape_javascript(render :partial => @comment) %>');
$('#comment_body').val('')
$('#comment_author').val('')

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="row">

    <div class="col-sm-4">
      <div class="fc-header-title"><h2>Recent Posts</h2></div>
      <% @recent_posts = Post.order("created_at DESC").limit(5) %>
      <% @recent_posts.each do |post| %>
        <li><%= link_to_unless_current post.title, post %></li>
      <% end %>
      <br>
    </div>

    <div class="col-sm-4">
    </div>

    <div class="col-sm-4">
      <div id="calendar"></div>
    </div>

  </div>

  <div class="row text-center">

    <p class="copyright">
      Made with
      <span class="ion-heart"></span>
      <span>by</span>
      <a href="http://sumninjacode.io"> Sumedha Pramod</a>
      <span>&#124;</span>
      <a href='https://github.com/pramodsum/ShesGotAWill/issues'>Issues</a>
    </p>
    
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <a href="./">
      <h1 class="blog-title"><center><%= content_for?(:title) ? yield(:title) : "Blog Template" %></center></h1>
      <br>
      <center><%=image_tag("placeholder.jpeg", height: "500",class:"img-responsive img-rounded")%></center>
      <br>
    </a>
    <%= render :partial => 'layouts/navbar' %>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav text-center">
      <li><a href="/posts">Posts</a></li>
      <li><a href="/archive">Archive</a></li>
      <li><a href="/about">About Me</a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Blog Template" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render :partial => 'layouts/header' %>

    <%= yield %>
   
    <%= render :partial => 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" %>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Cooking In Pajamas" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render :partial => 'layouts/header' %>
    <div class="main-content">
      <div class="container-fluid">
      <div class="post-index">
          <div class="posts-container">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= render :partial => 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="post-index">
  <div class="content-container row">
    <div class="col-xs-4">
      <%=image_tag("placeholder.jpeg", class:"img-responsive img-rounded")%>
    </div>
    <div class="col-xs-8">
      <div class="about-text"><h1>About Me</h1></div>
      <p>
        Put text here.
      </p>
    </div>
  </div>
</div>

app/views/pages/archive.html.erb
<div class="post-index">
  <div class="content-container row">
  </div>
</div>

app/views/posts/_post.html.erb
<center class="@post-header">
  <p class="title">
    <h1><%= @post.title %></h1>
  </p>
  <p class="date">
    <span class="ion-calendar"></span>
    <%= @post.created_at.strftime('%a') %>
    <%= @post.created_at.strftime('%B') %>
    <%= @post.created_at.strftime('%C') %>,
    <%= @post.created_at.strftime('%G') %> @
    <%= @post.created_at.strftime('%l') %>:<%= @post.created_at.strftime('%M') %> <%= @post.created_at.strftime('%p') %>
  </p>
</center>
<hr>
<p class="@post-content">
  <%= @post.content %>
</p>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <div class="post">
    <center class="post-header">
      <div class="title">
        <h1><%= link_to post.title, post_path(post) %></h1>
      </div>

      <div class="date">
        <span class="ion-calendar"></span>
        <%= post.created_at.strftime('%a') %>
        <%= post.created_at.strftime('%B') %>
        <%= post.created_at.strftime('%C') %>,
        <%= post.created_at.strftime('%G') %> @
        <%= post.created_at.strftime('%l') %>:<%= post.created_at.strftime('%M') %> <%= post.created_at.strftime('%p') %>
      </div>
    </center>

    <hr>
    
    <div class="post-content">
      <%= post.content %>
    </div>

    <br>

    <div class="label label-default"><%= post.comments.count %> comments</div>

  </div>
<% end %>

<!-- Default text if no posts -->
<% if @posts.count == 0 %>
  <center>
    <h1>No posts yet :(</h1>
  </center>
<% end %>

app/views/posts/index.html.erb
<div class="post-index">
  <div class="posts-container">
    <%= render :partial => 'posts' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid">

  <p id="notice"><%= notice %></p>

  <div class="post-index">
    <div class="posts-container">
      <div class="post">
        <%= render :partial => 'post' %>

        <h3>Comments</h3>
        <div id="comments">
          <%= render :partial => @post.comments %>
        </div>
        <%= form_for [@post, Comment.new], :remote => true do |f| %>
         <p>
           <%= f.text_area :body, :class => "form-control"%>
           <!--<%= f.text_field :author, :class => "form-control" %>-->
         </p>
         <p><%= f.submit "Add comment", :class => 'btn' %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>